### ISSUE TITLE
提案：環境変数をremote-patient-monitoring-dashboardと統一する

### ISSUE THREAD

**Issue by garasubo** [codeforjapan/remote-patient-monitoring-client#173]
APIへのURLを`VUE_APP_API_URL`に設定していますが、remote-patient-monitoring-dashboardと同じ`APP_URL`に統一したほうがデプロイのプロセスがわかりやすいと思いました

**Comment by kaizumaki** [comment]
ご提案ありがとうございます！clientはVueのプロジェクトなので、環境変数は先頭に `VUE_APP_` をつけるのがお作法なのですよね...
一方で、dashboardはnuxtなのでまたお作法が違うといった感じなのです。

**Comment by garasubo** [comment]
なるほど…難しい問題ですね。
デプロイのためのビルドコマンドも違ったのでちょっと困ったのですが、違うフレームワークを使っている以上しかたがないかもしれませんね
