### ISSUE TITLE
ログインURLが動かない

### ISSUE THREAD

**Issue by garasubo** [codeforjapan/remote-patient-monitoring-client#176]
ダッシュボードから生成されるログインURLでのログインがうまくいきません。
ローカル環境だと`http://localhost:8080/login/<token>`のようなURLが生成されて、`src/views/Login.vue`の内部で`handleLogin`メソッドが呼ばれることが期待されると思うのですが、APIの呼び出しがそもそもブラウザで発生していなかったので、`Login.vue`の問題だと思います。
Vueには疎いので間違っているかもしれません

**Comment by kaizumaki** [comment]
@garasubo ご報告ありがとうございます！私もローカル環境で試してみたところ、routerが `hash` モードなのでダッシュボードが生成するURLに不備があることがわかりました。
```
http://localhost:8080/login/<token>
```
ではなく、
```
http://localhost:8080/#/login/<token>
```
にすべきですね。
dashboard側の不具合なので、そちらのリポジトリで修正かけますね。

**Comment by garasubo** [comment]
環境変数の方に`/#`を足したら正しく動作することを確認しました。ありがとうございます！
